= Temporary auto-index page
//uncomment to generate temporary nav file contents on console.
//:antora-indexer-log-lists:

* Community

indexList::[level=2,relative=community/*.adoc]

** Board Reports

indexList::[level=3,relative=community/boardreports/*.adoc]

* Development

indexList::[level=2,relative=development/*.adoc]

* Documentation

indexList::[level=2,relative=documentation/*.adoc]

** Tools

indexList::[level=3,relative=documentation/tools/*.adoc]

** Tutorials

indexList::[level=3,relative=documentation/tutorials/*.adoc]

* Downloads

indexList::[level=2,relative=downloads/*.adoc]

** Archived Releases
*** 0.1-incubating

indexList::[level=4,relative=downloads/archived-releases/0.1-incubating/*.adoc]

*** 0.2-incubating

indexList::[level=4,relative=downloads/archived-releases/0.2-incubating/*.adoc]

*** 0.3-incubating

indexList::[level=4,relative=downloads/archived-releases/0.3/*.adoc]

** CT
*** 0.2-incubating

indexList::[level=4,relative=downloads/ct/0.2-incubating/*.adoc]

*** 0.3

indexList::[level=4,relative=downloads/ct/0.3/*.adoc]

*** 1.0.0

indexList::[level=4,relative=downloads/ct/1.0.0/*.adoc]

*** current-release (1.0??)

indexList::[level=4,relative=downloads/ct/current-release/*.adoc]

* Modules

indexList::[level=2,relative=modules/*.adoc]

** Samples

indexList::[level=3,relative=modules/samples/*.adoc]

** Transaction Control

indexList::[level=3,relative=modules/tx-control/*.adoc]

