:doctype: book

Title:     Board Report Notice:    Licensed to the Apache Software Foundation (ASF) under one            or more contributor license agreements.
See the NOTICE file            distributed with this work for additional information            regarding copyright ownership.
The ASF licenses this file            to you under the Apache License, Version 2.0 (the            "License");
you may not use this file except in compliance            with the License.
You may obtain a copy of the License at            .              http://www.apache.org/licenses/LICENSE-2.0            .            Unless required by applicable law or agreed to in writing,            software distributed under the License is distributed on an            "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY            KIND, either express or implied.
See the License for the            specific language governing permissions and limitations            under the License.

= February 2011 Board report

Aries delivers a set of pluggable Java components enabling an enterprise OSGi application programming model.

Aries 0.3 has now been released.
Aries Application 0.2.1 is being released to assist Geronimo.
This is the first time Aries has released a single module.

Now that the first full Aries release since graduation has happened, and that there is a desire to consider OSGi semantic versioning guidelines we are discussing whether releasing at a finer grained level is more appropriate.
There is much good discussion about what makes sense for Aries, with input from what happens in Felix, Sling and ACE.

Community update: largely unchanged since last month dev@ 117 subscribers, user@ 127 subscribers.
The dev@ list continues to be active with less traffic on the user@ list.
No new committers or PMC members since the January report.

There are no board level issues.
