= July 2013 Board report

Apache Aries delivers a set of pluggable Java components enabling an enterprise OSGi application programming model.

== Releases

* Apache Aries Subsystems Bundle 1.0.0

____
This is an 'uber' bundle form of the API and implementation (core) bundles of Aries Subsystems.
Together these are the reference implementation of the OSGi Subsystem Service Specification which "provides a declarative model for defining resource collections, including bundles, and an API for installing and managing those collections of resources." See OSGi Enterprise Release 5 specification chapter 134.
The 'uber' bundle is released for a convenience for people starting out with Subsystems.
____

== Project update

We have voted in John Ross as a member of the PMC.
No new committers since the last report.
Usage questions and interactions with other non-ASF projects continue to be asked on the user list, showing users are putting Aries to use in real world scenarios.

There are no board level issues.
